CREATE TABLE siba_szn_6_player_stats (
    Player VARCHAR,
    GP INTEGER,
    PPG FLOAT,
    RPG FLOAT,
    APG FLOAT,
    SPG FLOAT,
    BPG FLOAT,
    FGPercentage FLOAT,
    3PPercentage FLOAT,
    TOPG FLOAT,
    A_TO_Ratio FLOAT,
    PTS INTEGER,
    REB INTEGER,
    AST INTEGER,
    STL INTEGER,
    BLK INTEGER,
    FLS INTEGER,
    TO INTEGER,
    FGM INTEGER,
    FGA INTEGER,
    "3PM" INTEGER,
    3PA INTEGER,
    FGPercentage_1 FLOAT,
    3PPercentage_1 FLOAT
);